### ISSUE TITLE
Avoid deprecated functions

### ISSUE THREAD

**Issue by davidkarlsen** [FranzDiebold/github-env-vars-action#14]
When running the action you will see:
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

**Comment by FranzDiebold** [comment]
Thank you for the hint @davidkarlsen !

I updated the Action to [`v1.2.1`](https://github.com/FranzDiebold/github-env-vars-action/releases/tag/v1.2.1) (#16) so the warning should not appear any more.
Have fun working with `github-env-vars-action`! 🥳
