### ISSUE TITLE
The `set-env` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by wzalazar** [FranzDiebold/github-env-vars-action#17]
Hi! thanks for the package. 

I started used the package today and I received this issue, I don't know if there is any plan to fix them.

> Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Thanks in advance

**Comment by FranzDiebold** [comment]
Hi @wzalazar !
Thanks for your comment. Which version of `github-env-vars-action` are you using?
In version [`v1.2.1`](https://github.com/FranzDiebold/github-env-vars-action/releases/tag/v1.2.1) this warning should not appear any more. See https://github.com/FranzDiebold/github-env-vars-action/issues/14 for more information.
Have fun working with github-env-vars-action! 🥳

**Comment by wzalazar** [comment]
Thanks for your quick response, I'm using `v1.2.0`, I'm going to update. 

Thanks a lot! Nice Action!
