### ISSUE TITLE
Unable to find version `v1`

### ISSUE THREAD

**Issue by gabmontes** [FranzDiebold/github-env-vars-action#18]
Just tried to setup my workflow to pick any 1.x.x version of the action by simply specifying `@v1` instead of the exact version i.e. `@v1.2.1` and got this error:

```
Unable to resolve action `FranzDiebold/github-env-vars-action@v1`, unable to find version `v1`
```

Isn't it supported by this action?

PS: Very handy action. Thanks!!

**Comment by FranzDiebold** [comment]
Hi @gabmontes !

Thanks for your feedback.
I just added the [`v1`](https://github.com/FranzDiebold/github-env-vars-action/releases/tag/v1) tag, so you may now specify `@v1` and it will automatically pick the newest `v1.x.x` version! 💪

Have fun using `FranzDiebold/github-env-vars-action`! 🚀
