### ISSUE TITLE
Only works on linux

### ISSUE THREAD

**Issue by PazerOP** [FranzDiebold/github-env-vars-action#3]
If this can't be fixed easily so it runs on windows (and mac), I think the readme should be updated to mention its compatibility.

![image](https://user-images.githubusercontent.com/6569500/86496061-85420e00-bd30-11ea-9661-f83f19316458.png)

Step:
```
- uses: FranzDiebold/github-env-vars-action@v1.0.0
```

**Comment by FranzDiebold** [comment]
Hi @PazerOP! Thanks for your remark and for opening this issue! I now added a compatibility hint to the readme, see PR https://github.com/FranzDiebold/github-env-vars-action/pull/4.

**Comment by PazerOP** [comment]
If anyone else comes across this issue and just needs info about the current tag/branch, I ended up using https://github.com/benjlevesque/short-sha and https://github.com/olegtarasov/get-tag.

**Comment by FranzDiebold** [comment]
Hi @PazerOP ! I changed the action and it now supports **all Operating systems** :muscle: (Linux, macOS and Windows)! See PR https://github.com/FranzDiebold/github-env-vars-action/pull/5.
