### ISSUE TITLE
Title and Description of a PR

### ISSUE THREAD

**Issue by teebu** [FranzDiebold/github-env-vars-action#32]
Is it possible to add these to the ENV vars?

**Comment by FranzDiebold** [comment]
Hi @teebu !

Thanks for your feedback.

I just added `CI_PR_TITLE` and `CI_PR_DESCRIPTION` to the environment variables 😉 and published the new version [v2.3.0](https://github.com/FranzDiebold/github-env-vars-action/releases/tag/v2.3.0).

For an example see [this example action output](https://github.com/FranzDiebold/github-env-vars-action/pull/31/checks?check_run_id=2490588773).

Happy coding! 🚀
