### ISSUE TITLE
on a delete branch event, create var about deleted branch

### ISSUE THREAD

**Issue by llicour** [FranzDiebold/github-env-vars-action#41]
on a delete branch event, github CI does not set information about deleted branch in envvar
instead, CI_REF_NAME is always valuated to <default branch>, as delete workflow is executed on this branch
original branch is available at ${{ github.event.ref }}
It could be useful to have this data inside new envvars (if CI_EVENT_NAME==delete) CI_EVENT_REF_NAME & CI_EVENT_REF_NAME_SLUG
(in fact, in my used case, this is the slug version that interest me)

**Comment by FranzDiebold** [comment]
Hi @llicour,

thanks for using `github-env-vars-action`!

I'm afraid that the [`github` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) (such as `github.event`) is not available from within an action, so I probably cannot add it to this action.

Best regards!
