### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by jgwinner** [FranzDiebold/github-env-vars-action#42]
Hi - great addin, makes a lot of writing GitHub actions easier.

BUT ... I can't find anywhere to obtain the text of a commit message.

If a PR is squashed, the CI_PR_DESCRIPTION  will have all the commits, but I was hoping to emulate the GitHub slack app. It shows a commit message:

[1 new commit](http://example.com) pushed  to master by [whosyourdaddy](url)
`48f8e748 `- Item Maintenance V2 sort Feature (#186)
Pull request merged by [bossbaby](url)

> #186 Item Maintenance V2 sort Feature
> * message from commit
> * another message from commit
> [#197 linkToPR](url) | Aug 13th

Although now that I really look at it, some of the text comes from a PR, not the commit, so maybe even GitHub can't get the commit message? Yet the text after the code is only from the commit message.

Is it possible to get the commit message on a push action?

**Comment by FranzDiebold** [comment]
Hi @jgwinner!

Thanks for using `github-env-vars-action`!

The commit message is available in the [`github` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) using `${{ github.event.head_commit.message }}`, which you can directly use in your workflow.
However, this information seems not to be available *from within an action*, so I cannot add it to this action 😞.

I hope this helps you anyway!

Best regards!

**Comment by jgwinner** [comment]
Well thank you for a great and useful action!

> '${{ github.event.head_commit.message }}'

Ah, I looked everywhere. I actually was hoping to get a list of commit messages when a PR is submitted, but for regular pushes / commits, this will work perfectly. 

== John ==
