### ISSUE TITLE
Error: Cannot read property 'pull_request' of undefined

### ISSUE THREAD

**Issue by williarin** [FranzDiebold/github-env-vars-action#49]
The new release 2.5.0 seems to break on pull requests with this error:
`Error: Cannot read property 'pull_request' of undefined`

I haven't tried on master though.

Here's a failed job example: https://github.com/williarin/wordpress-interop/runs/7370315629?check_suite_focus=true#step:3:21

**Comment by yaldram** [comment]
Yes even I am getting this error. I used this variable - `CI_PR_SHA_SHORT`.

**Comment by FranzDiebold** [comment]
Hi @williarin,
thanks for reporting this issue!

I removed version `v2.5.0` and rolled back version `v2`.

So you can now use either version `v2.4.0` or `v2`.

**Comment by yaldram** [comment]
@iamstarkov Sir can we fix the above error. I wanted to work with the `CI_PR_SHA_SHORT` variable. Thanks

**Comment by iamstarkov** [comment]
@yaldram Sir we can, but not me in the next few days.

**Comment by yaldram** [comment]
@iamstarkov sure Sir take your time, thanks

**Comment by FranzDiebold** [comment]
Hi @williarin, @iamstarkov and @yaldram,

I have fixed the bug now and published a new version `v2.5.0`.

Can you confirm that `CI_PR_SHA_SHORT` and `CI_PR_SHA` are working now?

**Comment by yaldram** [comment]
@FranzDiebold Thanks a lot for fixing it Sir. It is working for me.

**Comment by FranzDiebold** [comment]
Sounds good!
