### ISSUE TITLE
*_SLUG envs are not truncated

### ISSUE THREAD

**Issue by TomaszG** [FranzDiebold/github-env-vars-action#52]
*_SLUG environment variables are commonly used as URLs or docker image tags. To make it happen without problems, a lot of systems also shorten them, e.g. GitLab's max length of SLUG is 63 bytes (https://docs.gitlab.com/ee/ci/variables/predefined_variables.html). Unfortunately, SLUG variables returned by this plugin are not shortened. Maybe it would be worth either:

1. have a max length of SLUG predefined, or
2. have a configuration option to define max SLUG length, or
3. add a shortened version of SLUG env vars.

**Comment by FranzDiebold** [comment]
Hi @TomaszG,

thanks for the issue and the idea!

I truncated all `*_SLUG` variables to 63 characters and published a new version [`v2.6.0`](https://github.com/FranzDiebold/github-env-vars-action/releases/tag/v2.6.0).
