### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by Nihisil** [FranzDiebold/github-env-vars-action#59]
GH action shows a warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: FranzDiebold/github-env-vars-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by jonathanlinat** [comment]
![image](https://github.com/FranzDiebold/github-env-vars-action/assets/14064112/0c6d3316-1667-46c1-8ccb-b623d8edbbcc)

**Comment by FranzDiebold** [comment]
Closed by #60 .
